version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: project-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network  # Подключаем к сети
    

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network  # Подключаем к сети
    environment:
      DATABASE_URL: postgresql://auth_user:auth_password@postgres:5432/auth_db
    depends_on:
      - postgres
volumes:
  postgres_data:
# Определение сети в корне файла
networks:
  app-network:
    driver: bridge